NAME = ex02

SRCS = main.cpp \
	Base.cpp

OBJS = $(SRCS:.cpp=.o)

HEADERS = Base.hpp \
	A.hpp \
	B.hpp \
	C.hpp

CC = c++
CFLAGS = -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(NAME)

%.o: %.cpp $(HEADERS)
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re

